
apiVersion: v1
kind: Service
metadata:
  name: shopify-converter
  namespace: shopify-converter
  labels:
    app: shopify-converter
    service: shopify-converter
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: shopify-converter

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopify-converter-v1
  namespace: shopify-converter
  labels:
    app: shopify-converter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopify-converter
      version: v1
  template:
    metadata:
      labels:
        app: shopify-converter
        version: v1
    spec:
      imagePullSecrets:
      - name: github-container-registry
      containers:
      - name: shopify-converter
        image: ghcr.io/valentine195/shopify-converter:{{ .Values.sha }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP